/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)rti_dl_buildid_cpp.h    generated by: makeheader    Wed Mar  9 22:30:28 2022
 *
 *		built from:	buildid_cpp.ifc
 */

#ifndef rti_dl_buildid_cpp_h
#define rti_dl_buildid_cpp_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIDISTRIBUTEDLOGCPP_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* rti_dl_buildid_cpp_h */
