/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_data_TDataWriter.h    generated by: makeheader    Wed Mar  9 22:40:05 2022
 *
 *		built from:	dds_cpp_data_TDataWriter.gen
 */

#ifndef dds_cpp_data_TDataWriter_h
#define dds_cpp_data_TDataWriter_h

#endif /* dds_cpp_data_TDataWriter_h */
