/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)persistence_buildid.h    generated by: makeheader    Wed Mar  9 23:16:48 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef persistence_buildid_h
#define persistence_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "PERSISTENCESERVICE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* persistence_buildid_h */
