/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)log_makeheader.h    generated by: makeheader    Wed Mar  9 22:29:37 2022
 *
 *		built from:	makeheader.ifc
 */

#ifndef log_makeheader_h
#define log_makeheader_h


  #ifdef __cplusplus
      extern "C" {
  #endif


  #if defined(RTI_WIN32) || defined(_WIN32)
    #pragma warning(disable:4068)
  #endif

  #define Public
  #define Package
  #define Peer
  #define RTI_PRIVATE static

  /*
   * Use this macro at the end of function declarations to warn if the function
   * returns a result that is never used.
   */
  #ifdef RTI_LINUX
    #define RTI_NODISCARD __attribute__((warn_unused_result))
  #else
    #define RTI_NODISCARD
  #endif

  /*
   * Use this macro at the end of static variable declarations to discard
   * unused variable warnings. Only supported for gcc >= 4.7 and clang.
   * This macro does not replace RTIOsapiUtility_unusedParameter and it must
   * be used ONLY for static variables.
   */
  #if (defined(__GNUC__) \
      && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ >= 7)))) \
      || defined(__clang__)
    #define RTI_MAYBE_UNUSED __attribute__ ((unused))
  #else
    #define RTI_MAYBE_UNUSED
  #endif

  #ifndef __cplusplus
  /*
   * #define public
   * #define package
   * #define peer
   * #define private	static
   */
  #endif	/* !__cplusplus */


  #ifdef __cplusplus
      }	/* extern "C" */
  #endif

#endif /* log_makeheader_h */
