/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)transport_tls_buildid.h    generated by: makeheader    Wed Mar  9 23:14:17 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef transport_tls_buildid_h
#define transport_tls_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTITRANSPORTTLS_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* transport_tls_buildid_h */
