/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)netio_configurator_impl.h    generated by: makeheader    Wed Mar  9 22:30:12 2022
 *
 *		built from:	configurator_impl.ifc
 */

#ifndef netio_configurator_impl_h
#define netio_configurator_impl_h


#ifdef __cplusplus
    extern "C" {
#endif


#define RTINetioConfiguratorUtil_generateShmemUuid(uuid, classid, hostid) \
        RTINetioConfiguratorUtil_generateDefaultNetworkAddress96( \
                uuid, \
                classid, \
                hostid, \
                0, \
                0, \
                0)


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* netio_configurator_impl_h */
