/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)monitor_buildid.h    generated by: makeheader    Wed Mar  9 22:42:03 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef monitor_buildid_h
#define monitor_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "RTIMONITORING_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* monitor_buildid_h */
