/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)core_version_buildid.h    generated by: makeheader    Wed Mar  9 22:30:21 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef core_version_buildid_h
#define core_version_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* core_version_buildid_h */
