/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_c_data_TDataReader.h    generated by: makeheader    Wed Mar  9 22:30:22 2022
 *
 *		built from:	dds_c_data_TDataReader.gen
 */

#ifndef dds_c_data_TDataReader_h
#define dds_c_data_TDataReader_h

#ifdef __cplusplus
    extern "C" {
#endif

#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dds_c_data_TDataReader_h */
