/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)reda_recordAdminArea.h    generated by: makeheader    Wed Mar  9 22:30:01 2022
 *
 *		built from:	recordAdminArea.ifc
 */

#ifndef reda_recordAdminArea_h
#define reda_recordAdminArea_h


  #include "reda/reda_recordAdminArea_impl.h"

#ifdef __cplusplus
    extern "C" {
#endif


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* reda_recordAdminArea_h */
