/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dl_driver_odbc_heap.h    generated by: makeheader    Wed Mar  9 22:29:46 2022
 *
 *		built from:	odbc_heap.ifc
 */

#ifndef dl_driver_odbc_heap_h
#define dl_driver_odbc_heap_h



#include "dl_driver/dl_driver_dll.h"
#include "rtisqlite/rtisqlite_odbc.h"

#ifdef __cplusplus
    extern "C" {
#endif


extern DLDRIVERDllExport
void DLDRIVERSqlAllocator_initialize(struct RTISqlAllocator *allocator);


#ifdef __cplusplus
    }	/* extern "C" */
#endif

#endif /* dl_driver_odbc_heap_h */
