/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)metp_buildid.h    generated by: makeheader    Wed Mar  9 22:41:49 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef metp_buildid_h
#define metp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "METPC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* metp_buildid_h */
