/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)dds_cpp_buildid.h    generated by: makeheader    Wed Mar  9 22:40:04 2022
 *
 *		built from:	buildid.ifc
 */

#ifndef dds_cpp_buildid_h
#define dds_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "NDDSCPP_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* dds_cpp_buildid_h */
