/* (c) Copyright 2003-2021, Real-Time Innovations, Inc. All rights reserved. */
/*
 * @(#)connext_cpp_buildid.h    generated by: makeheader    Wed Mar  9 22:41:55 2022
 *
 *		built from:	buildid.ifcxx
 */

#ifndef connext_cpp_buildid_h
#define connext_cpp_buildid_h


#ifndef RTI_BUILD_NUMBER_STRING
  #define RTI_BUILD_NUMBER_STRING "CONNEXTMSGCPP_BUILD_6.1.1.0_20220309T000000Z_RTI_REL"
#endif

#endif /* connext_cpp_buildid_h */
